### PR TITLE
Added a validator for datetime metadata fields

### LINKED ISSUE #297: Time- and Datepicker do not validate entered values
Date can be added with pretty incorrect formatting (see 1 and 2) and will still be accepted
        1. Add line of text, no error
        2. Replace numbers (at any point of date or time) with one letter, no error
-Sonia

### PR DESCRIPTION
**Pull request by Arnei**
For whatever reason, `mui-rff` disables the automatic datetime validation from material-ui, so we have to do the validation ourselves.

Resolves #297

### CODE REVIEW

**Comment by lkiesow** [comment]
Non-set dates are now also marked as invalid:


https://user-images.githubusercontent.com/1008395/119152684-d47c5480-ba50-11eb-8f5c-d6480f4e6392.mp4

**Comment by lkiesow** [comment]
Typing in a time, the field is also marked as invalid:

Screenshot from 2021-05-21 16-24-49

**Comment by Arnei** [comment]
> Typing in a time, the field is also marked as invalid:
> 

Curiously, when I enter "00:00" as a time it is not marked as invalid.

**Comment by lkiesow** [comment]
There still seem to be several cases where this breaks:


https://user-images.githubusercontent.com/1008395/119548034-15989f80-bd96-11eb-883c-1f3d7a1703fc.mp4

**Comment by lkiesow** [comment]
One Problem persists:
Screenshot from 2021-05-31 12-44-35

**Comment by Arnei** [comment]
The underlying issue here seems to be that the KeyboardDateTimePicker does not seem to be able to handle the empty string correctly (which is how Opencast represent "no date"). Should be fixed now.

**Pull request merged**
